OBJS = src/Main.cpp 

CC = g++ 

INCLUDE_PATHS = -IC:\SDL2-2.0.8\x86_64-w64-mingw32\include\SDL2

LIBRARY_PATHS = -LC:\SDL2-2.0.8\x86_64-w64-mingw32\lib 

COMPILER_FLAGS = -w -Wl,-subsystem,windows 

LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2 

OBJ_NAME = SDLTemplate

all: $(OBJS) 
	$(CC) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)